server:
  port: 8081
spring:
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
  datasource:
    url: jdbc:mysql://localhost:3306/lottery?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.demo.spring_redis.entity